"""Ajout du champ motif_refus

Revision ID: 416ecd036f9d
Revises: 0044d2de8ad8
Create Date: 2025-05-20 00:01:20.045604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416ecd036f9d'
down_revision = '0044d2de8ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motif_refus', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_column('motif_refus')

    # ### end Alembic commands ###
